### ISSUE TITLE
Find N by Kth node in Linked list.

### ISSUE THREAD

**Issue by AbhitBangar** [av1shek/All-Coding-Platform-Solutions#86]
Write a program to find the N by Kth node of linked list.

**Comment by AbhitBangar** [comment]
Would you plz assign me this issue...?

**Comment by AkanshuAich** [comment]
plz assign me the issue.

**Comment by priyanshuanand166** [comment]
Assign this to me as i am well versed in dsa and i am pretty confident that you will like my merge request.

**Comment by Rohans-7** [comment]
I would love to contribute plz assign this to me. I am sure you will love my solution and you will accept my request.

**Comment by Rohans-7** [comment]
Thank you !!

**Comment by NiranjanLangade** [comment]
Hello There,
Can you assign this issue to me I can solve this.

**Comment by pranotip283** [comment]
Can you assign me this issue?

**Comment by av1shek** [comment]
@NiranjanLangade @pranotip283 This solution is already added.
