### ISSUE TITLE
Compare two linked lists.

### ISSUE THREAD

**Issue by AbhitBangar** [av1shek/All-Coding-Platform-Solutions#88]
Write a program to compare two linked lists in C++

**Comment by AbhitBangar** [comment]
Would you plz assign me this issue...?

**Comment by AkanshuAich** [comment]
Plz can u assign me the issue .I want to contribute to the hactoberfest

**Comment by av1shek** [comment]
Sorry but since @AbhitBangar asked earlier I'm assigning this issue to him, @AkanshuAich you can create new issue I will assign you.

**Comment by av1shek** [comment]
@AkanshuAich I have created new issue, you can request there. I will assign you.

**Comment by av1shek** [comment]
Issue resolved
